sudo: true
language: generic
cache: apt

before_install:
  - echo "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main" | sudo tee /etc/apt/sources.list.d/llvm.list > /dev/null
  - sudo wget -O- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
  -
  - echo "deb https://debian.nabijaczleweli.xyz stable main" | sudo tee /etc/apt/sources.list.d/nabijaczleweli.list > /dev/null
  - sudo wget -O- https://debian.nabijaczleweli.xyz/nabijaczleweli.gpg.key | sudo apt-key add -
  -
  - sudo apt update

install:
  - sudo apt install --no-install-{suggest,recommend}s clang-9 libc++-9-dev libc++abi-9-dev pir-8-emu-binutils
  - export CC="clang-9 -stdlib=libc++" CXX="clang++-9 -stdlib=libc++"

script:
  - make -j$(grep '^processor' /proc/cpuinfo | wc -l)
